config/routes.rb
Rails.application.routes.draw do

  get 'card/new' => 'card#new'
  get 'card/show'
  get 'credit_cards/new'
  get 'credit_cards/show'

  root to: 'items#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new"
    get "/log_out" => "users#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :signup, only:[:new, :create] do
    collection do
      get 'user_info_input'
      get 'phone_number_authentication'
      get 'address_input'
      get 'payment' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :profiles, only:[:edit, :show, :update] do
    member do
      get :edit2
    end
  end

  # resources :users

  # 商品用ルーティング
  resources :items, only:[:create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    collection do
      get :sell                        # 商品出品ページ
      get 'buy/:id' => 'items#buy'     # 商品購入ページ
      get :pay
      get 'category/:id' => 'items#category'     # カテゴリーページ
      match 'search' => 'items#search', via: [:get, :post]  # 商品検索ページ
    end
    
  end

  # Ajax通信用
  namespace :api do
    get "select_child", to: "categorys#select_child"
    get "display_size", to: "categorys#display_size"
    get "select_burden", to: "categorys#select_burden"
    get "search_brand", to: "categorys#search_brand"
  end

  # クレカ関連
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay',    to: 'card#pay'
      post 'buy/:id'  => 'card#buy'
    end
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  require "payjp"

  before_action :validates_user_info_input, only: :phone_number_authentication # user_info_inputのバリデーション
  before_action :validates_phone_number_authentication, only: :address_input # phone_number_authenticationのバリデーション
  before_action :validates_address_input, only: :payment # address_inputのバリデーション

  def user_info_input
    @user = User.new # 新規インスタンス作成
  end

  def phone_number_authentication
    # user_info_inputで入力された値をsessionに保存
    session[:nickname]              = user_params[:nickname]
    session[:email]                 = user_params[:email]
    session[:password]              = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:lastname_kanji]        = user_params[:lastname_kanji]
    session[:firstname_kanji]       = user_params[:firstname_kanji]
    session[:lastname_kana]         = user_params[:lastname_kana]
    session[:firstname_kana]        = user_params[:firstname_kana]
    session[:birthday]              = birthday_params
    @user = User.new # 新規インスタンス作成
  end

  def address_input
    # phone_number_authenticationで入力された値をsessionに保存
    session[:cellphone_number]      = user_params[:cellphone_number]
    @prefectures = Prefecture.all
    @user = User.new # 新規インスタンス作成
    @user.build_address
  end

  def payment
    # address_inputで入力された値をsessionに保存
    session[:address_attributes]    = user_params[:address_attributes]
    @user = User.new # 新規インスタンス作成
  end

  def done
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  def create
    payjp_token = payjp_params.present? ? payjp_params[:payjp_token] : nil
    @user = User.new(
      nickname:                       session[:nickname], # sessionに保存された値をインスタンスに渡す
      email:                          session[:email],
      password:                       session[:password],
      password_confirmation:          session[:password_confirmation],
      lastname_kanji:                 session[:lastname_kanji], 
      firstname_kanji:                session[:firstname_kanji], 
      lastname_kana:                  session[:lastname_kana], 
      firstname_kana:                 session[:firstname_kana], 
      birthday:                       session[:birthday],
      cellphone_number:               session[:cellphone_number],
    )
    @user.build_address(session[:address_attributes])

    if @user.save
      # ログインするための情報を保管
      session[:id] = @user.id
      if payjp_token
        create_card(payjp_token, @user.id)
      else
        redirect_to done_signup_index_path
      end
    else
      render user_info_input_signup_index_path
    end
  end

  def validates_user_info_input
    # user_info_inputで入力された値をsessionに保存
    session[:nickname]              = user_params[:nickname]
    session[:email]                 = user_params[:email]
    session[:password]              = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:lastname_kanji]        = user_params[:lastname_kanji]
    session[:firstname_kanji]       = user_params[:firstname_kanji]
    session[:lastname_kana]         = user_params[:lastname_kana]
    session[:firstname_kana]        = user_params[:firstname_kana]
    session[:birthday]              = birthday_params

    # バリデーション用に、仮でインスタンスを作成する
    @user = User.new(
      nickname:                       session[:nickname], # sessionに保存された値をインスタンスに渡す
      email:                          session[:email],
      password:                       session[:password],
      password_confirmation:          session[:password_confirmation],
      lastname_kanji:                 session[:lastname_kanji], 
      firstname_kanji:                session[:firstname_kanji], 
      lastname_kana:                  session[:lastname_kana], 
      firstname_kana:                 session[:firstname_kana], 
      birthday:                       session[:birthday],
    )
    # 仮で作成したインスタンスのバリデーションチェックを行う
    render user_info_input_signup_index_path unless @user.valid?(:validates_user_info_input)
  end

  def validates_phone_number_authentication
    # phone_number_authenticationで入力された値をsessionに保存
    session[:cellphone_number]      = user_params[:cellphone_number]
    @user = User.new(
      nickname:                       session[:nickname], # sessionに保存された値をインスタンスに渡す
      email:                          session[:email],
      password:                       session[:password],
      password_confirmation:          session[:password_confirmation],
      lastname_kanji:                 session[:lastname_kanji], 
      firstname_kanji:                session[:firstname_kanji], 
      lastname_kana:                  session[:lastname_kana], 
      firstname_kana:                 session[:firstname_kana], 
      birthday:                       session[:birthday],
      cellphone_number:               session[:cellphone_number] # session2
    )
    # 仮で作成したインスタンスのバリデーションチェックを行う
    render phone_number_authentication_signup_index_path unless @user.valid?(:validates_phone_number_authentication)
  end 

  def validates_address_input
    @prefectures = Prefecture.all
    # address_inputで入力された値をsessionに保存
    session[:address_attributes]    = user_params[:address_attributes]
    @user = User.new(
      nickname:                       session[:nickname], # sessionに保存された値をインスタンスに渡す
      email:                          session[:email],
      password:                       session[:password],
      password_confirmation:          session[:password_confirmation],
      lastname_kanji:                 session[:lastname_kanji], 
      firstname_kanji:                session[:firstname_kanji], 
      lastname_kana:                  session[:lastname_kana], 
      firstname_kana:                 session[:firstname_kana], 
      birthday:                       session[:birthday],
      cellphone_number:               session[:cellphone_number], # session2
      address_attributes:             session[:address_attributes], # session3
    )
    # 仮で作成したインスタンスのバリデーションチェックを行う
    render address_input_signup_index_path unless @user.valid?(:validates_address_input)
  end 

  private
    def user_params
      params.require(:user).permit(
        :nickname, 
        :email, 
        :password, 
        :password_confirmation, 
        :lastname_kanji, 
        :firstname_kanji, 
        :lastname_kana, 
        :firstname_kana, 
        :cellphone_number,

        address_attributes: [:id, :zip_code, :prefecture_id, :jusho_shikuchoson, :jusho_banchi, :jusho_tatemono, :phone_number]
      )
    end

    def birthday_params
      # パラメータ取得
      date = params[:birthday]
  
      # ブランク時のエラー回避のため、ブランクだったら何もしない
      if date["birthday(1i)"].empty? && date["birthday(2i)"].empty? && date["birthday(3i)"].empty?
        return
      end
  
      # 年月日別々できたものを結合して新しいDate型変数を作って返す
      Date.new(date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i)
    end

    def payjp_params
      if params.has_key?(:payjp_token)
        params.permit(:payjp_token)
      else
        return nil
      end
    end

    # payjpとCardのデータベース作成を実施。card_controller.rbのpayアクションに相当
    def create_card(payjp_token, user_id) 
      Payjp.api_key = Rails.application.credentials[:api]
      customer = Payjp::Customer.create(
        card: payjp_token,
        metadata: {user_id: user_id}
        )
      @card = Card.new(user_id: user_id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to done_signup_index_path
      else
        redirect_to action: "payment"
      end
    end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/address_input.html.haml
#wrapper

  .header-email-registration
    .header-email-registration__logo
      = link_to '' do 
        = image_tag 'logo.svg', class: 'registration-header-logo'
    .progress-bar
      %ul
        %li
          会員情報
          .progress-status__done.red
        %li
          電話番号認証
          .progress-status.red
        %li.active
          お届け先住所入力
          .progress-status.red
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status

  -# 住所入力フォーム
  = form_with model: @user, local: true, url: payment_signup_index_path, method: :get, html: {class: 'third-wrapper__box'} do |f|
    = hidden_field_tag :current_step, 'address_input'
    .user-input
      .user-input__message
        住所入力
      .user-input__container

        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              お名前
              %span.hissu 必須
            .user-input__container__sell-contents__form-group__inputname
              = f.text_field :cellphone_number, value: "#{session[:lastname_kanji]}"
              = f.text_field :cellphone_number, value: "#{session[:firstname_kanji]}"

        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              お名前カナ
              %span.hissu 必須
            .user-input__container__sell-contents__form-group__inputname
              = f.text_field :cellphone_number, value: "#{session[:lastname_kana]}"
              = f.text_field :cellphone_number, value: "#{session[:firstname_kana]}"

        = f.fields_for :address do |address|
          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                郵便番号
                %span.hissu 必須
              .user-input__container__sell-contents__form-group__inputname
                = address.text_field :zip_code, placeholder: '　例) 123-4567'

          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                都道府県
                %span.hissu 必須
              .user-input__container__sell-contents__form-group__inputname
                = address.select :prefecture_id, @prefectures.map { |pref| [pref.name, pref.id] }, {include_blank: "---"}, {class: "contents-item__container__sell-contents__form-box__select-wrap--select prefecture-box-fix"}
          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                市町村
                %span.hissu 必須
              .user-input__container__sell-contents__form-group__inputname
                = address.text_field :jusho_shikuchoson, placeholder: '　例) 横浜市緑区'

          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                番地
                %span.hissu 必須
              .user-input__container__sell-contents__form-group__inputname
                = address.text_field :jusho_banchi, placeholder: '　例) 青山1-1-1'

          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                建物名
                %span.steppagefixstep3 任意
              .user-input__container__sell-contents__form-group__inputname
                = address.text_field :jusho_tatemono, placeholder: '　例) 柳ビル103'

          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                電話
                %span.steppagefixstep3 任意
              .user-input__container__sell-contents__form-group__inputname
                = address.text_field :phone_number, placeholder: '　例) 09012345678'

        .user-input__container__sell-btn.steppagefix.steppagefixstep3padding
          = f.submit '次へ進む', class: 'nextbotton'

  = render 'devise/shared/devise-footer'

app/views/signup/done.html.haml
#wrapper

  .header-email-registration
    .header-email-registration__logo
      = link_to '' do 
        = image_tag 'logo.svg', class: 'registration-header-logo'
    .progress-bar
      %ul
        %li
          会員情報
          .progress-status__done.red
        %li
          電話番号認証
          .progress-status.red
        %li
          お届け先住所入力
          .progress-status.red
        %li
          支払い方法
          .progress-status.red
        %li.active
          完了
          .progress-status.red

  .user-input
    .user-input__message
      会員登録完了
    .user-input__container
      %p.steppagefixstepdonecenter
        ありがとうございます。<br>
        登録が完了しました。

      .user-input__container__sell-btn.steppagefix.steppagefixstep3padding
        -# %button.user-input__container__sell-btn--btn-red メルカリをはじめる
        = link_to "メルカリをはじめる", root_path, class: 'user-input__container__sell-btn--btn-red'

  = render 'toppage/toppage-footer'

  = render 'devise/shared/devise-footer'

app/views/signup/payment.html.haml
#wrapper

  .header-email-registration
    .header-email-registration__logo
      = link_to '' do 
        = image_tag 'logo.svg', class: 'registration-header-logo'
    .progress-bar
      %ul
        %li
          会員情報
          .progress-status__done.red
        %li
          電話番号認証
          .progress-status.red
        %li
          お届け先住所入力
          .progress-status.red
        %li.active
          支払い方法
          .progress-status.red
        %li
          完了
          .progress-status

  -# 支払い方法フォーム
  = form_with local: true, url: "/signup", method: :post, html: {name: "inputForm", class: 'forth-main-wrapper__box', id: 'charge-form'} do |f|
    .user-input
      .user-input__message
        支払い方法
      .user-input__container

        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              カード番号
              %span.hissu 必須
            .user-input__container__sell-contents__form-group__inputname
              = f.text_field :number, placeholder: "半角数字のみ" ,maxlength: "16", type: "text", class: "number user-input__container__sell-contents__form-group__inputname--input", id: "card_number"
              
              = image_tag 'PEPSized_Visa.png', class: 'credit-card-icon'
              = image_tag 'PEPSized_Mastercard.png', class: 'credit-card-icon'
              = image_tag 'PEPSized_JCB.png', class: 'credit-card-icon'
              = image_tag 'PEPSized_AmericanExpress02.png', class: 'credit-card-icon'
              = image_tag 'PEPSized_DinersClub02.png', class: 'credit-card-icon'
              = image_tag 'PEPSized_Discover.png', class: 'credit-card-icon'

        .user-input__birthday.steppagefixstep4padding
          %label.label--small
            有効期限
          %span.hissu 必須
          .inpout-box-six
            %select.exp_month{name: "exp_month", type: "text", style: "width: 100px; height: 50px;", id: "exp_month"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月
            %select.exp_year{name: "exp_year", type: "text", style: "width: 100px; height: 50px;", id: "exp_year"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年

        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              セキュリティコード
              %span.hissu 必須
            .user-input__container__sell-contents__form-group__inputname
              = f.text_field :cvc, class: "cvc user-input__container__sell-contents__form-group__inputname--input", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              -# %input.user-input__container__sell-contents__form-group__inputname--input{name: "name", type: "text", placeholder: " カード背面4桁もしくは3桁の番号"}

        .user-input__about-user-info.steppagefixstep4padding2
          = fa_icon 'question-circle', class: 'kiyaku--blue'
          = link_to 'カード裏面の番号とは？', '#', class: 'kiyaku--blue'

        #card_token
          = f.submit "次へ進む", class: "nextbotton", id: "token_submit"
          = link_to "後で登録", signup_index_path, method: :post, class:'nextbotton', style: "background-color: grey; border-color: grey;"
          -# .user-input__container__sell-btn.steppagefix.steppagefixstep3padding
          -#   = f.submit '次へ進む', class: 'nextbotton'

  = render 'devise/shared/devise-footer'

app/views/signup/phone_number_authentication.html.haml
#wrapper

  .header-email-registration
    .header-email-registration__logo
      = link_to '' do 
        = image_tag 'logo.svg', class: 'registration-header-logo'
    .progress-bar
      %ul
        %li
          会員情報
          .progress-status__done.red
        %li.active
          電話番号認証
          .progress-status.red
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status

  -# 電話番号の確認
  = form_with model: @user, local: true, url: address_input_signup_index_path, method: :get, html: {class: 'second-wrapper__box'} do |f|
    .user-input
      .user-input__message
        電話番号の確認
      .user-input__container
        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              携帯電話の番号 
            .user-input__container__sell-contents__form-group__inputname
              = f.text_field :cellphone_number, placeholder: '　携帯電話の番号を入力'
        .user-input__sort-message
          %p
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          

        .user-input__container__sell-btn.steppagefix
          = f.submit 'SMSを送信する', class: 'nextbotton'
          %p.steppagefixstep2
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。

        .user-input__about-user-info
          = link_to '電話番号の確認が必要な理由', '#', class: 'kiyaku--blue'
          = fa_icon 'chevron-right', class: 'kiyaku--blue'

  = render 'devise/shared/devise-footer'

app/views/signup/user_info_input.html.haml
#wrapper

  // #step1用のヘッダー
  .header-email-registration
    .header-email-registration__logo
      = link_to '' do 
        = image_tag 'logo.svg', class: 'registration-header-logo'
    .progress-bar
      %ul
        %li.active
          会員情報
          .progress-status__done.red
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status

  -# 会員情報入力フォーム
  = form_with model: @user, local: true, url: phone_number_authentication_signup_index_path, method: :get, html: {class: 'first-main__box'} do |f|
    .user-input
      .user-input__message
        会員情報入力
      .user-input__container

        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              ニックネーム
              %span.hissu 必須
            .user-input__container__sell-contents__form-group
              = f.text_field :nickname, placeholder: '　例) メルカリ太郎'

        .user-input__container__sell-contents
          .user-input__container__sell-contents__form-group
            %label.label--small
              メールアドレス
              %span.hissu 必須
            .user-input__container__sell-contents__form-group__inputname
              = f.email_field :email, placeholder: '　PC・携帯どちらでも可'

        -# メールアドレスとSNS認証（Google, Facebook）での表示切り替え
        - if @user.email == ""
          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                パスワード
                %span.hissu 必須
              .user-input__container__sell-contents__form-group__inputname
                = f.password_field :password, placeholder: '　7文字以上'

          .user-input__container__sell-contents
            .user-input__container__sell-contents__form-group
              %label.label--small
                パスワード (確認)
                %span.hissu 必須
              .user-input__container__sell-contents__form-group__inputname
                = f.password_field :password_confirmation, placeholder: '　7文字以上'

        - else
          = f.hidden_field :password, placeholder: '　7文字以上'
          = f.hidden_field :password_confirmation, placeholder: '　7文字以上'

        .user-input__sort-message
          %h1
            本人確認
          %p
            安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。

        .user-input__namekanji
          %label.label--small
            お名前(全角)
            %span.hissu 必須
          .name-box
            = f.text_field :lastname_kanji, placeholder: '　例) 山田', class: 'field-namebox'
            = f.text_field :firstname_kanji, placeholder: '　例) 彩', class: 'field-namebox'

        .user-input__namehira
          %label.label--small
            お名前カナ(全角) 
            %span.hissu 必須
          .name-box
            = f.text_field :lastname_kana, placeholder: '　例) ヤマダ', class: 'field-namebox'
            = f.text_field :firstname_kana, placeholder: '　例) アヤ', class: 'field-namebox'

        .user-input__birthday
          %label.label--small
            生年月日
            %span.hissu 必須
          .birthday-box
            = (sprintf(f.date_select(:birthday, prefix:'birthday',with_css_classes:'XXXXX', prompt:"--",use_month_numbers:true, start_year:Time.now.year, end_year:1900, date_separator:'%s'),'年','月')+'日').html_safe

        .user-input__sort-message2
          %p
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。

        .recaptcha
            
        .user-input__container__sell-btn.steppagefix
          %div
            %p.kiyaku
            <center>「次へ進む」のボタンを押すことにより、
            %a.kiyaku--blue{href: '#'}>利用規約
            に同意したものとみなします</center>
          = f.submit '次へ進む', class: 'nextbotton'
        

        .user-input__about-user-info
          = link_to '本人情報の登録について', '#', class: 'kiyaku--blue'
          = fa_icon 'chevron-right', class: 'kiyaku--blue'

  = render 'devise/shared/devise-footer'