config/routes.rb
Rails.application.routes.draw do

  get 'card/new' => 'card#new'
  get 'card/show'
  get 'credit_cards/new'
  get 'credit_cards/show'

  root to: 'items#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new"
    get "/log_out" => "users#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :signup, only:[:new, :create] do
    collection do
      get 'user_info_input'
      get 'phone_number_authentication'
      get 'address_input'
      get 'payment' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :profiles, only:[:edit, :show, :update] do
    member do
      get :edit2
    end
  end

  # resources :users

  # 商品用ルーティング
  resources :items, only:[:create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    collection do
      get :sell                        # 商品出品ページ
      get 'buy/:id' => 'items#buy'     # 商品購入ページ
      get :pay
      get 'category/:id' => 'items#category'     # カテゴリーページ
      match 'search' => 'items#search', via: [:get, :post]  # 商品検索ページ
    end
    
  end

  # Ajax通信用
  namespace :api do
    get "select_child", to: "categorys#select_child"
    get "display_size", to: "categorys#display_size"
    get "select_burden", to: "categorys#select_burden"
    get "search_brand", to: "categorys#search_brand"
  end

  # クレカ関連
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay',    to: 'card#pay'
      post 'buy/:id'  => 'card#buy'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]


  has_one :address
  has_many :items
  has_one :card
  accepts_nested_attributes_for :address

  # いいね機能
  has_many :likes, dependent: :destroy

# SNS認証関係
  has_many :sns_credentials, dependent: :destroy

# item、transactとのアソシエーション
  has_many :buyer_transacts, class_name: 'Transact', foreign_key: 'buyer_id'
  has_many :seller_transacts, class_name: 'Transact', foreign_key: 'seller_id'

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # user_info_input入力項目
  validates :nickname,                presence: true, length: {maximum: 20}, on: :validates_user_info_input
  validates :email,                   presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, on: :validates_user_info_input
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :validates_user_info_input
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :validates_user_info_input
  validates :lastname_kanji,          presence: true, on: :validates_user_info_input
  validates :firstname_kanji,         presence: true, on: :validates_user_info_input
  validates :lastname_kana,           presence: true, on: :validates_user_info_input
  validates :firstname_kana,          presence: true, on: :validates_user_info_input
  validates :birthday,                presence: true, on: :validates_user_info_input

  # phone_number_authentication入力項目
  validates :cellphone_number,        presence: true, on: :validates_phone_number_authentication

  # item、transactとのバリデーション
  validates :items, associated: true
  validates :buyer_transacts, associated: true
  validates :seller_transacts, associated: true


  # SNS認証関係
  @pass = Devise.friendly_token[0, 7]
  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first
    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        password: @pass,
        password_confirmation: @pass,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    return { user: user ,sns: sns}
  end

  def self.with_sns_data(auth, snscredential)
    # user = User.where(id: snscredential.user_id).first
    user = User.find(snscredential.user_id)
    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
        password: @pass,
        password_confirmation: @pass,
      )
    end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      session[:provider] = @sns[:provider]
      session[:uid] = @sns[:uid]
      render template: "/signup/user_info_input"
    end
  end

  def failure
    redirect_to root_path and return
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def mypage

  end

  def destroy

  end

  def new

  end
    
  def person_info
    @prefectures = Prefecture.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage-side-menu.html.haml
.mypage-main__side-menu
  %nav.mypage-main__side-menu__box
    %ul.side-menu-mypage
      %li.mypage-nav-list-item.active
        = link_to "マイページ", profile_path(current_user.id)
      %li.mypage-nav-list-item
        お知らせ
      %li.mypage-nav-list-item
        やることリスト
      %li.mypage-nav-list-item
        いいね！一覧
      %li.mypage-nav-list-item
        = link_to '出品する', sell_items_path
      %li.mypage-nav-list-item
        出品した商品 - 出品中
      %li.mypage-nav-list-item
        出品した商品 - 取引中
      %li.mypage-nav-list-item
        出品した商品 - 売却済み
      %li.mypage-nav-list-item
        購入した商品 - 取引中
      %li.mypage-nav-list-item
        購入した商品 - 過去の取引
      %li.mypage-nav-list-item
        ニュース一覧
      %li.mypage-nav-list-item
        評価一覧
      %li.mypage-nav-list-item
        ガイド
      %li.mypage-nav-list-item
        お問い合わせ

    %h3
      メルペイ
    %ul
      %li.mypage-nav-list-item
        売上・振込申請
      %li.mypage-nav-list-item
        ポイント
    %h3
      設定
    %ul
      %li.mypage-nav-list-item
        = link_to "プロフィール", edit_profile_path(current_user.id)
      %li.mypage-nav-list-item
        発送元・お届け先住所変更
      %li.mypage-nav-list-item
        = link_to "支払い方法", new_card_path
      %li.mypage-nav-list-item
        メール/パスワード
      %li.mypage-nav-list-item
        = link_to "本人情報", edit2_profile_path(current_user.id)
      %li.mypage-nav-list-item
        電話番号の確認
      %li.mypage-nav-list-item
        = link_to "ログアウト", "/log_out"

app/views/users/destroy.html.haml
= render 'toppage/header'

.logout-main
  = render 'users/mypage-side-menu'

  -# 修正前
  -# .logout-main__right
  -#   = form_with class: 'l-single-inner', action: "https://www.mercari.com/jp/logout/", method: "POST", novalidate: "novalidate" do
  -#     .l-single-content
  -#       -# %button.btn-default.btn-red{type: "submit"} ログアウト
  -#       -# %input{name: "__csrf_value", type: "hidden", value: "b66f76f0af6533a7ef8ffd1e819cd400923f651ad5edd7/640b653da1b612bbbe5f9e0cf00d1fc4ec682f3ad5a5480b2f7b7e98409d8a3023f092f7096722b7c00"}
  -#       = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn-default btn-red'
  
  -# 修正後
  .logout-main__right
    .l-single-content.l-single-inner
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn-destroy'

    -# 確認用のためにコメントアウト
    -# - if user_signed_in?
    -#   【ログイン中】
    -#   = current_user.nickname
    -#   <br>
    -#   = link_to "ログアウトする", destroy_user_session_path, method: :delete
    -# - else
    -#   【ログアウト中】<br>
    -#   = link_to "ログインページへ", sign_in_path, class: 'post'
    -#   = link_to "新規登録ページへ", sign_up_path, class: 'post'

= render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'

app/views/users/person_info.html.haml
= render 'toppage/header'


.person_info-main
  = render 'users/mypage-side-menu'

  .person_info-main__right
    %h2.person_info-main__right__title
      本人情報の登録
    = form_with class: 'l-single-inner', action: :'https://www.mercari.com/jp/mypage/identification/save/', method: :POST, local: true do |f|
      %div
        %p
          お客さまの本人情報をご登録ください。
          %br
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.text-right
          = link_to "/jp/help_center/article/495/" do
            本人確認書類のアップロードについて
      .form-group
        %label
          お名前
        %p
          土屋悠平
      .form-group
        %label
          お名前カナ
        %p
          ツチヤ ユウヘイ
      .form-group
        %label
          生年月日
        %p
          1999/04/06
      .form-group
        %label
          郵便番号
        %span.form-arbitrary
          任意
        = f.text_field :zip_code, placeholder: '例）1234567', type: 'text', class: 'input-default'
      .form-group
        %label
          都道府県
        %span.form-arbitrary
          任意
        .select-wrap
          = f.select :prefecture_id, @prefectures.map { |pref| [pref.name, pref.id] },{include_blank: "---"}, class: 'select-default'

      .form-group
        %label
          市町村
        %span.form-arbitrary
          任意
        = f.text_field :jusho_shikuchoson, placeholder: "例) 横浜市緑区", type: "text", class: 'input-default'

      .form-group
        %label
          番地
        %span.form-arbitrary
          任意
        = f.text_field :jusho_banchi, placeholder: "例) 青山1−1−1", type: "text", class: 'input-default'

      .form-group
        %label
          建物名
        %span.form-arbitrary
          任意
        = f.text_field :jusho_tatemono,placeholder: "例) 柳ビル103", type: "text", class: 'input-default'

        %button.btn-default.btn-red{type: "submit"}
          登録する

      .form-group.text-right
        %p
          = link_to "/jp/help_center/article/423/", target: "_blank" do
            本人情報の登録について
            %i.icon-arrow-right

















= render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'

app/views/users/profile.html.haml
= render 'toppage/header'

.bread-crumbs
  .bread-crumbs__ii
    - breadcrumb :mypage
    = breadcrumbs  separator: " &rsaquo; "

.mypage-main
  = render 'users/mypage-side-menu'

  -# プロフィール画面
  .mypage-main__right-contents
    .profile-contents
      .profile-contents__box.profile-title
        プロフィール
      .profile-contents__box.profile-bg
        .setting-profile
          .setting-profile__box
            %figure
              = image_tag '//static.mercdn.net/images/member_photo_noimage_thumb.png'
          .setting-profile__box
            %input.profile-box-size
      .profile-contents__box
        %textarea{name: "introduction", class: "introduction-box", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
      .profile-contents__box
        %button.profile-button
          変更する

= render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'