config/routes.rb
Rails.application.routes.draw do

  get 'card/new' => 'card#new'
  get 'card/show'
  get 'credit_cards/new'
  get 'credit_cards/show'

  root to: 'items#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new"
    get "/log_out" => "users#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :signup, only:[:new, :create] do
    collection do
      get 'user_info_input'
      get 'phone_number_authentication'
      get 'address_input'
      get 'payment' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :profiles, only:[:edit, :show, :update] do
    member do
      get :edit2
    end
  end

  # resources :users

  # 商品用ルーティング
  resources :items, only:[:create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    collection do
      get :sell                        # 商品出品ページ
      get 'buy/:id' => 'items#buy'     # 商品購入ページ
      get :pay
      get 'category/:id' => 'items#category'     # カテゴリーページ
      match 'search' => 'items#search', via: [:get, :post]  # 商品検索ページ
    end
    
  end

  # Ajax通信用
  namespace :api do
    get "select_child", to: "categorys#select_child"
    get "display_size", to: "categorys#display_size"
    get "select_burden", to: "categorys#select_burden"
    get "search_brand", to: "categorys#search_brand"
  end

  # クレカ関連
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay',    to: 'card#pay'
      post 'buy/:id'  => 'card#buy'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  belongs_to :user
  belongs_to :category
  belongs_to :size, optional: true
  belongs_to :brand, optional: true
  belongs_to :burden

  # いいね機能
  has_many :likes, dependent: :destroy
  def like_user(id)
    likes.find_by(user_id: id)
  end

  has_one :transact, dependent: :destroy
  accepts_nested_attributes_for :transact
  # has_many :comments  # コメント機能が実装できた際に有効化すること

  # null falseのバリデーション
  with_options presence: true do
    validates :name
    validates :price
    validates :torihiki_info
    validates :product_state
    validates :description
    validates :shipping_days
    validates :user_id
    validates :prefecture_id
    validates :category_id
    validates :burden_id
  end
  # 入力値範囲のバリデーション
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :prefecture_id, numericality: { less_than_or_equal_to: 48 }
  validates :torihiki_info, numericality: { less_than_or_equal_to: 2 }
  validates :product_state, numericality: { less_than_or_equal_to: 6 }
  validates :shipping_days, numericality: { less_than_or_equal_to: 2 }
  validates :category_id, numericality: { less_than_or_equal_to: 1326 }
  validates :size_id, numericality: { less_than_or_equal_to: 66 }, allow_blank: true
  validates :brand_id, numericality: { less_than_or_equal_to: 10102 }, allow_blank: true
  validates :burden_id, numericality: { less_than_or_equal_to: 14 }

  # アソシエーションのバリデーション
  validates :images, associated: true, presence: true
  validates :transact, associated: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


  @@torihiki_info_list = ["出品中", "取引中", "売却済"]
  @@product_state_list = ["新品", "未使用", "傷なし", "やや傷あり", "やや傷汚れ", "傷汚れ", "状態悪し"]
  @@shipping_days_list = ["1~2日", "2~3日", "4~7日"]

  # torihiki_info、shipping_days、product_stateの配列を返すメソッドを定義
  def torihiki_info_list
    @@torihiki_info_list
  end

  def product_state_list
    @@product_state_list
  end

  def shipping_days_list
    @@shipping_days_list
  end

  # torihiki_info、shipping_days、product_stateを文字列に変換するメソッドを定義
  def display_torihiki_info
    return self.torihiki_info_list[self.torihiki_info]
  end

  def display_product_state
    return self.product_state_list[self.product_state]
  end

  def display_shipping_days
    return self.shipping_days_list[self.shipping_days]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, only: [:sell, :create, :edit, :update, :destroy, :buy]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :buy]
  before_action :set_ancestry, only: [:sell, :edit]

  def index
    @items = Item.all.limit(10)

    @radys_items = Item.where(category_id: 160..338).order("created_at DESC").limit(10)
    @mens_items = Item.where(category_id: 339..468).order("created_at DESC").limit(10)
    @electronics_items = Item.where(category_id: 955..1029).order("created_at DESC").limit(10)
    @hoby_items = Item.where(category_id: 766..866).order("created_at DESC").limit(10)
  end

  def sell
    @item = Item.new
    @item.images.build
  end

  def create
    @item = Item.new(item_params)
    @item.build_transact(seller_id: current_user.id)
    if @item.save
      redirect_to root_path
    else
      @item.images = []
      @item.images.build
      set_ancestry
      render :sell
    end
  end

  def show
    @images = @item.images
  end

  def edit
    if @item.user == current_user
      @image = Image.new
    else
      redirect_to item_path(params[:id])
    end
  end

  def update
    update_params = item_params
    image_del_list = delete_images if delete_images
    image_update_list = update_params[:images_attributes] if update_params[:images_attributes]
    update_params.delete(:images_attributes)
    update_params = update_params.merge(size_id: nil) unless update_params.has_key?(:size_id)
    update_params = update_params.merge(brand_id: nil) unless update_params.has_key?(:brand_id)
    if image_update_list
      image_update_list.each do |img|
        Image.create(img.merge(item_id: @item.id))
      end
    end
    if image_del_list
        image_del_list.each do |image_id|
        Image.find(image_id).destroy
      end
    end
    if @item.update(update_params)
      redirect_to item_path(params[:id])
    else
      set_ancestry
      render :edit
    end
  end

  def buy
    if @item.user == current_user
      redirect_to item_path(params[:id])
    else
      @user = @item.user
      @card = Card.new
    end
  end

  def destroy
    if @item.user == current_user
      if @item.destroy
        redirect_to root_path, notice: '商品を削除しました'
      else
        @images = @item.images
        flash.now[:alert] = "商品削除に失敗しました"
        render :show
      end
    else
      redirect_to item_path(params[:id])
    end
  end

  def category
    @selected_cat = Category.find(params[:id])
    # 第1カテゴリー(レディース、メンズ、etc)
    if @selected_cat.depth == 1
      cat_list = @selected_cat.indirect_ids
    # 第2カテゴリー
    elsif @selected_cat.depth == 2
      cat_list = @selected_cat.child_ids
    # 第3カテゴリー
    elsif @selected_cat.depth == 3
      cat_list = [@selected_cat.id]
    end
    @items = Item.where(category_id: cat_list).limit(10)
  end

  def search
    search_params = top_search_params == nil ? params[:q] : top_search_params
    @q = Item.ransack(search_params)
    @category = Category.find(1)
    @size = Size.find(1)   # 服サイズ
    @lists = Item.new
    @items = @q.result(distinct: true).includes(:burden)
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :category_id, :size_id, :brand_id, :product_state, :burden_id, :prefecture_id, :shipping_days, :price, images_attributes: [:image] ).merge(good: 0, user_id: current_user.id, torihiki_info: 0)
  end

  def delete_images
    if params.has_key?(:delete_ids)
      return params.require(:delete_ids)
    else
      return nil
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_ancestry
    @category = Category.find(1)
    @burden = Burden.roots
    @prefectures = Prefecture.all
  end

  def top_search_params
    if params.has_key?(:name_cont)
      params.slice(:name_cont)
    else
      return nil
    end
  end

end

app/views/items/_electronics.html.haml
.ladys-new-items
  .ladys-new-items__top
    %h3.ladys-new-items__top__title
      家電・スマホ・カメラ
    = link_to root_path, class: 'ladys-new-items__top__more' do
      もっと見る ＞
  .ladys-new-items__bottom
    .ladys-new-items__bottom__grid
      - @electronics_items.each do |i|
        .index-item
          = link_to item_path(i), class: 'index-item__link' do
            .index-item__link__small-box
              .index-item__link__small-box__top
                %p
                  ¥
                  = i.price
                = image_tag i.images[0].image.url, alt: 'next', class:'jojo'
              .item-small-box__bottom
                %span.item-name111
                  = i.name

app/views/items/_hoby.html.haml
.ladys-new-items
  .ladys-new-items__top
    %h3.ladys-new-items__top__title
      おもちゃ・ホビー・グッズ
    = link_to root_path, class: 'ladys-new-items__top__more' do
      もっと見る ＞
  .ladys-new-items__bottom
    .ladys-new-items__bottom__grid
      - @hoby_items.each do |i|
        .index-item
          = link_to item_path(i), class: 'index-item__link' do
            .index-item__link__small-box
              .index-item__link__small-box__top
                %p
                  ¥
                  = i.price
                = image_tag i.images[0].image.url, alt: 'next', class:'jojo'
              .item-small-box__bottom
                %span.item-name111
                  = i.name

app/views/items/_item.html.haml
.like-link
  = render partial: 'likes/like_links', locals:{ item: item }

app/views/items/_mens.html.haml
.ladys-new-items
  .ladys-new-items__top
    %h3.ladys-new-items__top__title
      メンズ
    = link_to root_path, class: 'ladys-new-items__top__more' do
      もっと見る ＞
  .ladys-new-items__bottom
    .ladys-new-items__bottom__grid
      - @mens_items.each do |i|
        .index-item
          = link_to item_path(i), class: 'index-item__link' do
            .index-item__link__small-box
              .index-item__link__small-box__top
                %p
                  ¥
                  = i.price
                = image_tag i.images[0].image.url, alt: 'next', class:'jojo'
              .item-small-box__bottom
                %span.item-name111
                  = i.name

app/views/items/_radys.html.haml
.ladys-new-items
  .ladys-new-items__top
    %h3.ladys-new-items__top__title
      レディース
    = link_to root_path, class: 'ladys-new-items__top__more' do
      もっと見る ＞
  .ladys-new-items__bottom
    .ladys-new-items__bottom__grid
      - @radys_items.each do |i|
        .index-item
          = link_to item_path(i), class: 'index-item__link' do
            .index-item__link__small-box
              .index-item__link__small-box__top
                %p
                  ¥
                  = i.price
                = image_tag i.images[0].image.url, alt: 'next', class:'jojo'
              .item-small-box__bottom
                %span.item-name111
                  = i.name

app/views/items/buy.html.haml
.buy-body
  .buy-header
    %h1
      = link_to root_path, class: 'header-link' do
        = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2687693852'
  .buy-main
    %section.buy-main__all
      %h2.buy-item-title
        購入内容の確認
      %section.buy-content.buy-item
        .buy-content-inner
          .buy-content-inner__on
            %h3.buy-item-image
              = image_tag @item.images[0].image.url
            %p.buy-item-name.bold
              = @item.name
          = form_with  url: '/card/buy/:id', method: :get, class: 'buy-form' do |f|
            %P.buy-price-ja.bold
              ¥
              = @item.price.to_s(:delimited)
              %span.item-shipping-fee.f14.bold
                = @item.burden.parent.name.sub(/（出品者負担）/,"").sub(/（購入者負担）/,"")
              %ul.buy-accordion.not-have
                %li.accordion-parent
                  .accordion-toggle
                    ポイントはありません
              %ul.buy-price-table
                %li.buy-price-row.buy-you-pay.bold
                  .buy-price-cell
                    支払い金額
                  .buy-price-cell
                    %span{data:{buy:{pay: "14200"}}}
                      ¥
                      = @item.price.to_s(:delimited)
              = link_to "購入する", "/card/buy/#{@item.id}", class:'btn-default btn-red bold', method: :post

      %section.buy-content.buy-user-info
        .buy-content-inner
          %h3 配送先
          %address.buy-user-info-text
            〒
            = @user.address.zip_code
            %br/
            = @user.address.jusho_shikuchoson
            = @user.address.jusho_banchi
            = @user.address.jusho_tatemono
            %br/
            = @user.nickname
          %p.buy-user-info-text
          = link_to root_path, class: 'buy-user-info-fix' do
            %span 変更する
            %i.icon-arrow-right

      %section.buy-content.buy-user-info{"data-buy" => "pay-method"}
        .buy-content-inner
          %h3 支払い方法
          %p.buy-user-info-text
            %br/
            \2222333232323/
            %figure

          = link_to "https://www.mercari.com/jp/transaction/card/m52817775865/?_s=U2FsdGVkX19qf-PmE2bU0OHPpU5wPM7kVTl_0V1IXeJBV3Y0eF6vlebhfhmdjnc9V2RHWfk4yr5p2r2GEZXcb0B-_lUoryvfWE6xiMhZVxRxTn3tRSVjP1yIajNYwpbf", class: 'buy-user-info-fix' do
            %span 変更する
            %i.icon-arrow-right

      = render 'devise/shared/devise-footer'

app/views/items/category.html.haml
.mercari
  = render 'toppage/header'

  .body

    .bread-crumbs
      .bread-crumbs__ii.cat-crum
        - breadcrumb :"item#{@selected_cat.id}"
        = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

    .category-link
      .category-link__linkbox
        .category-link__linkbox__top
          %ul.category-link__linkbox__top--cat-ul.clearfix
            - if @selected_cat.depth == 3
              - @selected_cat.siblings.each do |cat|
                %li.category-link__linkbox__top--cat-ul--cat-li
                  = link_to cat.name, "/items/category/#{cat.id}", class: "category-link__linkbox__top--cat-ul--cat-li--cat-a"
            - else
              - @selected_cat.children.each do |cat|
                %li.category-link__linkbox__top--cat-ul--cat-li
                  = link_to cat.name, "/items/category/#{cat.id}", class: "category-link__linkbox__top--cat-ul--cat-li--cat-a"


    .product
      .ladys-new-items
        .ladys-new-items__top
          %h3.ladys-new-items__top__title
            = "#{@selected_cat.name} の商品一覧"
          = link_to root_path, class: 'ladys-new-items__top__more' do
            もっと見る ＞
        .ladys-new-items__bottom
          .ladys-new-items__bottom__grid
            - @items.each do |i|
              .index-item
                = link_to item_path(i), class: 'index-item__link' do
                  .index-item__link__small-box
                    .index-item__link__small-box__top
                      %p
                        ¥
                        = i.price
                      = image_tag i.images[0].image.url, alt: 'next', class:'jojo'
                    .item-small-box__bottom
                      %span.item-name111
                        = i.name

  = render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'

app/views/items/index.html.haml
.mercari
  = render 'toppage/header'

  .body
    .slide
      .slide__box
        = image_tag "top-banner-camp-4f3fd88c685e8932d7dde2ad3a8336ba.jpg", alt: '', class: 'slide__box__image1', id: "mypic"
      %div.prevbtn
        = image_tag "prev.png", alt: 'prev'
      %div.nextbtn
        = image_tag "next.png", alt: 'next'

    .popular-category
      %h2.popular-category__top
        人気のカテゴリー
      .popular-category__bottom
        %ul.popular-category__bottom__box
          %li.popular-category__bottom__box__ladys
            = link_to "レディース", "items/category/2"
          %li.popular-category__bottom__box__mens
            = link_to "メンズ", "items/category/3"
          %li.popular-category__bottom__box__electronics
            = link_to "家電・スマホ・カメラ", "items/category/9"
          %li.popular-category__bottom__box__toy
            = link_to "おもちゃ・ホビー・グッズ", "items/category/7"

    .product
      = render 'items/radys'

      = render 'items/mens'

      = render 'items/electronics'

      = render 'items/hoby'


  = render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'

app/views/items/search.html.haml
.mercari
  = render 'toppage/header'

  .body
    .product
      .search-product
        = search_form_for @q, url: search_items_path do |f|
          %h3{style: "font-size: 16px;"} 詳細検索
          .search-product__form-group
            = f.label :name_cont, "キーワードを追加する"
            %br
            = f.search_field :name_cont, {class: "search-product__form-group--input-text"}
          .search-product__form-group{id: "select-category-box"}
            = f.label :category_id, "カテゴリーを選択する"
            %select{class: "search-product__form-group--select-cat" , id: "select-cat1", name: "category_id"}
              %option{value: nil} すべて
              - @category.children.each do |cat|
                %option{value: cat.id}
                  = cat.name

          .search-product__form-group
            %label{name: "brand"} ブランド名から探す
            %br
            %input{class: "search-product__form-group--input-text", name: "brand", type: "text", id: "brand-text", style: "width: 225px; height: 28px;"}
              .div
                .ul{class: "brand-ul", style: "display: none;"}
          .search-product__form-group
            = f.label :size_id, "服サイズを指定する"
            %br
            = f.select :size_id_eq, @size.children.map { |size| [size.name, size.id] }, {include_blank: "---"}, {class: "search-product__form-group--select-cat"}
          .search-product__form-group
            = f.label :price, "価格"
            %br
            = f.number_field :price_gteq, class: "search-product__form-group--price-box", placeholder: "¥ Min"
            〜
            = f.number_field :price_lteq, class: "search-product__form-group--price-box", placeholder: "¥ Max"
          .search-product__form-group
            = f.label :product_state_eq_any, "商品の状態"
            %br
            %div.check-box-div
              %input{type: "checkbox", name: "product_state", class: "search-checkbox", id: "checkbox-all"}
                %p{nam: "product_state_eq_any", class: "check-box-label"} すべて
            - @lists.product_state_list.each_with_index do |state, i|
              %div.check-box-div
                = f.check_box :product_state_eq_any, {multiple: true, include_hidden: false, class: "search-checkbox", id: "product_state"}, i
                %p{nam: "product_state_eq_any", class: "check-box-label"} #{state}
          .search-product__form-group
            = f.label :torihiki_info_eq_any, "販売状況"
            %br
            %div.check-box-div
              %input{type: "checkbox", name: "torihiki_info", class: "search-checkbox", id: "checkbox-all"}
              %p{nam: "torihiki_info_eq_any", class: "check-box-label"} すべて
            - @lists.torihiki_info_list.each_with_index do |info, j|
              %div.check-box-div
                = f.check_box :torihiki_info_eq_any, {multiple: true, include_hidden: false, class: "search-checkbox", id: "torihiki_info"}, j
                %p{nam: "torihiki_info_eq_any", class: "check-box-label"} #{info}
                  
          = link_to "クリア", search_items_path , class: "search-clear-button"
          = f.submit "検索", {class: "search-submit-button"} 

      .ladys-new-items.search-right
        .ladys-new-items__top
          %h3.ladys-new-items__top__title
            = "検索結果 の商品一覧"
        .ladys-new-items__bottom
          .ladys-new-items__bottom__grid.search-card
            - @items.each do |i|
              .index-item.search-index-item
                = link_to item_path(i), class: 'index-item__link' do
                  .index-item__link__small-box.search-small-box
                    .index-item__link__small-box__top.search-card-height
                      %p.search-price
                        ¥
                        = i.price
                      = image_tag i.images[0].image.url, alt: 'next', class:'jojo-search'
                    .item-small-box__bottom
                      %span.item-name111
                        = i.name
                          
                          

  = render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'

app/views/items/show.html.haml
= render 'toppage/header'

.flash-box
  .flash-box__lower
  .flash-box__upper
    = render 'layouts/flash'

.item-deteal
  .item-deteal__box
    %h1.item-deteal__box__title
      = @item.name
    .item-deteal__box__item
      .item-deteal__box__item__left
        .left__top

          = image_tag @item.images[0].image.url, alt: '', class: 'slide__box__image3'
        .left__down
          .left__down__iir
            - @images.each_with_index do |image, index|
              .left__down__iir__gffk
                = image_tag image.image.url, alt: '', class: 'left__down__iir__gffk__image', id: @item.id
      %table.item-detail-table
        %tbody
          %tr
            %th 出品者
            %td.td-padding
              = link_to "#", class: "kiyaku--bule-underline" do
                = @item.user.nickname
              .yyy.icon-top
                .item-user-ratings
                  = fa_icon 'smile-o', {class: "good-icons--pink"}
                  %span 40
                .item-user-ratings.icon-margin
                  = fa_icon 'meh-o', {class: "good-icons--orange"}
                  %span 0
                .item-user-ratings.icon-margin
                  = fa_icon 'frown-o', {class: "good-icons--blue"}
                  %span 0
          %tr
            %th カテゴリー
            %td.td-padding
              - if @item.category.parent.parent
                = link_to "#", class: "kiyaku--bule-underline" do
                  %div
                    = @item.category.parent.parent.name #親
              = link_to "#" do
                .item-detail-table-sub-category{class: "kiyaku--bule-underline"}
                  %i.icon-arrow-right
                  = "＞" + @item.category.parent.name        #子
              = link_to "#" do
                .item-detail-table-sub-sub-category{class: "kiyaku--bule-underline"}
                  %i.icon-arrow-right
                  = "＞" + @item.category.name               #孫
          - if @item.brand
            %tr
              %th ブランド
              %td.td-padding
                %a{href: "#", class: "kiyaku--bule-underline"}
                  %div
                    = @item.brand.name
          - if @item.size
            %tr
              %th 商品のサイズ
              %td.td-padding
                = @item.size.name
          %tr
            %th 商品の状態
            %td.td-padding
              = @item.display_product_state
          %tr
            %th 配送料の負担
            %td.td-padding
              = @item.burden.parent.name
          %tr
            %th 配送の方法
            %td.td-padding
              = @item.burden.name
          %tr
            %th 配送元地域
            %td.td-padding
              %a{href: "#", class: "kiyaku--bule-underline"}
                = @item.prefecture.name
          %tr
            %th 発送日の目安
            %td.td-padding
              = @item.display_shipping_days

    - if @item.user != current_user
      .item-deteal__box__price
        %span.oooo
          ¥
          = @item.price.to_s(:delimited)
        %span.rrrr
          （税込）
        %span.wwww
          = @item.burden.parent.name.sub(/（出品者負担）/,"").sub(/（購入者負担）/,"")
      - if @item.transact.buyer_id
        = link_to "#", class:'kkooko', style: "background-color: grey;"do
          売り切れました
      - else
        = link_to "/items/buy/#{@item.id}", class:'kkooko'do
          購入画面に進む
      .item-deteal__box__description
        %p.item-deteal__box__description__idjs
          = @item.description
    - else
      .item-deteal__box__price
        %span.oooo
          ¥
          = @item.price.to_s(:delimited)
        %span.rrrr
          （税込）
        %span.wwww
          = @item.burden.parent.name.sub(/（出品者負担）/,"").sub(/（購入者負担）/,"")
      .item-deteal__box__description
        %p.item-deteal__box__description__idjs
          = @item.description
      - if @item.transact.buyer_id
        = link_to "#", class:'kkooko--edit-grey' do
          商品が購入されました。発送してください。
      - else
        = link_to edit_item_path(@item.id), class:'kkooko--edit' do
          商品の編集
        = link_to "この商品を削除する", "/items/#{@item.id}", method: :delete, data: { confirm: "確認\n削除すると二度と復活できません\n本当に削除しますか？" }, class: 'kkooko--edit-grey'

    .item-button-container.clearfix
      - if current_user && @item.user != current_user
        .item-button-left
          %button.item-button.item-button-like{"data-ga" => "element", "data-ga-category" => "LIKE", "data-ga-label" => "like!", "data-id" => "m38799137224", "data-toggle" => "like", :name => "like!", :type => "button"}
            #js-grid-juicy-projects
              = render @item
          .item-button-report
            %span 不適切な商品の報告
          %input{:name => "like_add_url", :type => "hidden", :value => "#"}/
          %input{:name => "like_del_url", :type => "hidden", :value => "#"}/
          %input{:name => "__csrf_value", :type => "hidden", :value => "#"}/
        .item-button-right
          = link_to '#', target: '_blank' do
            %i.icon-lock
            %span あんしん・あんぜんへの取り組み
      - else

= render 'toppage/toppage-footer'

= render 'toppage/exhibition-button'