config/routes.rb
Rails.application.routes.draw do

  get 'card/new' => 'card#new'
  get 'card/show'
  get 'credit_cards/new'
  get 'credit_cards/show'

  root to: 'items#index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new"
    get "/log_out" => "users#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :signup, only:[:new, :create] do
    collection do
      get 'user_info_input'
      get 'phone_number_authentication'
      get 'address_input'
      get 'payment' # ここで、入力の全てが終了する
      get 'done' # 登録完了後のページ
    end
  end

  resources :profiles, only:[:edit, :show, :update] do
    member do
      get :edit2
    end
  end

  # resources :users

  # 商品用ルーティング
  resources :items, only:[:create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
    collection do
      get :sell                        # 商品出品ページ
      get 'buy/:id' => 'items#buy'     # 商品購入ページ
      get :pay
      get 'category/:id' => 'items#category'     # カテゴリーページ
      match 'search' => 'items#search', via: [:get, :post]  # 商品検索ページ
    end
    
  end

  # Ajax通信用
  namespace :api do
    get "select_child", to: "categorys#select_child"
    get "display_size", to: "categorys#display_size"
    get "select_burden", to: "categorys#select_burden"
    get "search_brand", to: "categorys#search_brand"
  end

  # クレカ関連
  resources :card, only: [:new, :show, :destroy] do
    collection do
      post 'pay',    to: 'card#pay'
      post 'buy/:id'  => 'card#buy'
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user,dependent: :destroy
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  before_action :authenticate_user!

  def new
    if current_user.card
      redirect_to action: "show" unless current_user.card.nil?
    end
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.credentials[:api]
    if params['payjp_token'].blank?
      redirect_to action: "new"
    else
      user_id = current_user.id
      customer = Payjp::Customer.create(
        # description: '登録テスト', #なくてもOK
        # email: current_user.email, #なくてもOK
        card: params['payjp_token'],
        metadata: {user_id: user_id}
        ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: user_id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to profile_path(current_user.id), notice: 'クレジットカードを登録しました'
      else
        redirect_to action: "pay"
      end
    end
  end

  def destroy #PayjpとCardデータベースを削除します
    card = current_user.card
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:api]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      redirect_to profile_path(current_user.id)
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = current_user.card
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:api]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_id = card.id
    end
  end

  def buy #クレジット購入
    card = current_user.card

    if card.blank?
      redirect_to action: "new"
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    else
      @item = Item.find(params[:id])
      # 購入した際の情報を元に引っ張ってくる
      # card = Card.where(user_id: current_user.id).first
      card = current_user.card
      # テーブル紐付けてるのでログインユーザーのクレジットカードを引っ張ってくる
      # Payjp.api_key = "sk_test_0e2eb234eabf724bfaa4e676"
      Payjp.api_key = Rails.application.credentials[:api]
      # キーをセットする(環境変数においても良い)

      Payjp::Charge.create(
        amount: @item.price, #支払金額
        customer: card.customer_id, #顧客ID
        currency: 'jpy', #日本円
      )
      # ↑商品の金額をamountへ、cardの顧客idをcustomerへ、currencyをjpyへ入れる
      @item.build_transact(buyer_id: current_user.id, seller_id: @item.user.id)
      @item.torihiki_info = 2
      # if @item.update(torihiki_info: 2, buyer_id: current_user.id)
      if @item.save
        flash[:notice] = '購入しました。'
        redirect_to controller: "items", action: 'show'
      else
        flash[:alert] = '購入に失敗しました。'
        # redirect_to controller: "products", action: 'show'
        redirect_to controller: "items", action: 'buy'
      end
      #↑この辺はこちら側のテーブル設計どうりに色々しています
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
= render 'toppage/header'

.cardnew-main
  = render 'users/mypage-side-menu'

  .l-content
    %h2.l-chapter-head
      クレジットカード情報入力
    = form_tag(pay_card_index_path(from: 'profiles'), method: :post, id: 'charge-form',  name: "inputForm", class:"l-single-inner registration-form") do
      .form-group
        %label カード番号
        %span.form-require 必須
        = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        %ul.signup-card-list
          %li
            = image_tag 'PEPSized_Visa.png', class: 'credit-card-icon'
          %li
            = image_tag 'PEPSized_Mastercard.png', class: 'credit-card-icon'
          %li
            = image_tag 'PEPSized_JCB.png', class: 'credit-card-icon'
          %li
            = image_tag 'PEPSized_AmericanExpress02.png', class: 'credit-card-icon'
          %li
            = image_tag 'PEPSized_DinersClub02.png', class: 'credit-card-icon'
          %li
            = image_tag 'PEPSized_Discover.png', class: 'credit-card-icon'


      .signup-form-expire
        %label 有効期限
        %span.form-require 必須
        .inpout-box-six
          %select.exp_month{name: "exp_month", type: "text", id: "exp_month"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月
          %select.exp_year{name: "exp_year", type: "text", id: "exp_year"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年

      .form-group.ee
        %label セキュリティコード
        %span.form-require 必須
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      #card_token
      = submit_tag "追加する", id: "token_submit", class: "nextbotton"

= render 'toppage/toppage-footer'

= render 'toppage/exhibition-button' 

app/views/card/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag("/card/#{@card_id}", method: :delete, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する